[package]
name = "v4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.62"
json = "0.12.4"
reqwest = { version = "0.11.11", features = ["blocking"] }